title: Aimilee Manriquez # your name (or website title) here
logo: "/images/Self.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Scientist with 2+ years of experience in empirical psychological research and 3+ years of commercial experience in banking, finance, and risk analysis. 
  I have a Bachelor's of Science in Psychology, a minor in Advertising, and have also obtained a Post-Graduate Diploma in Data Science & Business Analytics
  from the McCombs School of Business.
  
  <br><br>
  <a href="https://eportfolio.mygreatlearning.com/aimilee-tran">View My Academic E-Portfolio</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
