title: Aimilee Manriquez # your name (or website title) here
logo: "/images/Self New.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I'm Aimilee! That's pronounced like "Emily". I'm an aspiring data scientist with 6+ years of commercial experience in banking, finance, and risk analysis with a background in empirical psychological research. I am passionate about mental health, education, and cross-cultural collaboration. 
  
  <br><br>
  My educational credentials include a Bachelor's of Science in Psychology, a minor in Advertising, and I have also obtained a Post-Graduate Diploma in 
  Data Science & Business Analytics from the McCombs School of Business.
  
  <br><br>
  <a href="https://eportfolio.mygreatlearning.com/aimilee-tran">View My Academic E-Portfolio</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
